title: Neel's Wesbite
name: Neel Gupta
orcid: 0009-0000-1263-4009
email: ngupta1@uw.edu
markdown: kramdown

plugins:
  - jekyll-scholar
  - jekyll-seo-tag
  - jekyll-paginate

scholar:
  style: apa
  locale: en
  bibliography: papers.bib
  bibliography_template: bib
