title: Neel Gupta
name: Neel Gupta
orcid: 0009-0000-1263-4009
email: ngupta1@uw.edu
markdown: kramdown

plugins:
  - jekyll-scholar
  - jekyll-seo-tag
  - jekyll-paginate

scholar:
  style: apa
  locale: en
  source: ./_bibliography
  bibliography: papers.bib
  bibliography_template: bib
  sort_by: year,month
  order: descending
